#!/usr/bin/python2.7
# bump alpha-5
import sys; sys.path.insert(0, '.pylib')
import time, os, threading, traceback, hashlib, math, random, socket
from datetime import datetime, timedelta
from collections import namedtuple, defaultdict
from itertools import count
from six import integer_types
from hosted import config, node, device, monotonic_time
from hosted.scheduler import verified_timezone, utc_to_local
from hosted.p2p import OrderedEventGroup

device.reboot()

