#!/usr/bin/python2.7
import sys; sys.path.insert(0, 'pylib')
from hosted import device
import time
config.restart_on_update()
device.gpio.setup_pin(26, direction="out")
device.gpio.set_pin_value(26,  high=True)
